### ISSUE TITLE
编译时报错Ignoring feed 'poweroff' - index missing

### ISSUE THREAD

**Issue by NagaseKouichi** [esirplayground/luci-app-poweroff#1]
使用lean大佬的最新代码，在feeds.conf.default中添加了这个luci-app-poweroff源。

在update feeds时提示：

> Collecting target info: doneUpdating feed 'poweroff' from 'https://github.com/esirplayground/luci-app-poweroff.git' ...
> Cloning into './feeds/poweroff'...
> Create index file './feeds/poweroff.index' 
> grep: feeds/poweroff/Makefile:#: No such file or directory
> grep: call: No such file or directory
> grep: BuildPackage: No such file or directory
> grep: OpenWrt: No such file or directory
> grep: buildroot: No such file or directory
> grep: signature/Makefile: No such file or directory
> /workdir/openwrt/feeds/poweroff.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.

在install feeds时提示：

> Installing all packages from feed poweroff.
> Ignoring feed 'poweroff' - index missing
> Ignoring feed 'poweroff' - index missing
> Ignoring feed 'poweroff' - index missing
> Ignoring feed 'poweroff' - index missing

在make menuconfig的时候菜单里面没有luci-app-poweroff

请问这个是什么原因呢？

**Comment by esirplayground** [comment]
不要用feeds update，直接git clone到package

**Comment by NagaseKouichi** [comment]
> 不要用feeds update，直接git clone到package

谢谢大佬，我试一试
